Google calendar integration
1ptqc-KD-97bsBG-pVJG/SyncMaster pull request #12
Opened 2024-11-24 22:49 UTC by alanzhangithub

# Google Calendar Integration

This PR adds the ability to add appointments directly to Google Calendar with properly formatted details.

## Changes
- Added GoogleCalendarService to handle calendar link generation
- Formatted appointment details for Google Calendar events
- Customized event title to show "SyncMaster Appointment"
- Included all relevant appointment details in event description

## Testing
- Verified date/time formatting matches appointment details
- Tested with and without customer names
- Confirmed all appointment details are properly included in event description

Will continue to work on other stuff.
It looks good to me though, be tough on my critique for this PR. Also pls approve iCal PR lol.

2024-11-24 22:50 UTC, alanzhangithub commented
<img width="871" alt="Screenshot 2024-11-24 at 17 50 21" src="https://github.com/user-attachments/assets/6c780eb1-c50d-4c40-aea4-4ae3445fdb0f">
<img width="871" alt="Screenshot 2024-11-24 at 17 50 34" src="https://github.com/user-attachments/assets/37032dc2-0d95-4647-80f1-874b7905bd64">

2024-12-02 23:57 UTC, 1ptqc-KD-97bsBG-pVJG requested changes
While all of the Google Calendar related code looks good to me, it looks like this PR was based off of the still open [Added iCal support for appointments](https://github.com/1ptqc-KD-97bsBG-pVJG/SyncMaster/pull/10), so it's pretty hard to determine which code is new. More importantly however, the "Add To Google Calendar" button shown on this PR does not appear for me when testing locally, meaning I also cannot verify it's functionality. Please take another look when you get a chance and maybe consider waiting until [Added iCal support for appointments](https://github.com/1ptqc-KD-97bsBG-pVJG/SyncMaster/pull/10) is closed to request another review here. Thanks!

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/1fee9625-ec87-4a57-98b0-1b5c28fb1c01">

2024-12-02 23:57 UTC, 1ptqc-KD-97bsBG-pVJG commented on app/views/appointments/show.html.erb
I'm not seeing any code here to actually display the "Add To Google Calendar Button" displayed on the PR, could be wrong though

2024-12-03 00:28 UTC, alanzhangithub commented on app/views/appointments/show.html.erb
Yeah I think I messed up on one of my local deployments. Happens when I'm travelling and forget to stash a commit or if I work at my desktop and forget and do something else on the mac. 

I did notice that actually I need to have PR-10 merged first before I can work on this since there is some conflicts. 
I just fixed PR#10 so feel free to merge and then I can go ahead and fix this real quick.

2024-12-06 20:47 UTC, closed without merging